[project]
name = "project_fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "pandas>=2.3.0",
    "pydantic>=2.11.5",
    "scikit-learn>=1.7.0",
    "uvicorn>=0.34.3",
]
